#pragma once
#include <windows.h>
#include <string>

enum class Lang { English, Nederlands, Polski };

inline Lang gCurrentLang = Lang::English;

inline const wchar_t* T(int id);

enum StringId {
  S_GO = 1,
  S_SEARCH,
  S_SETTINGS,
  S_GOOGLE,
  S_PINTEREST,
  S_ROBLOX,
  S_DISCORD,
  S_SPOTIFY,
  S_DOWNLOADS,
  S_DARK,
  S_IMPORT,
  S_EXPORT,
  S_NEW_TAB,
  S_LIGHT_MODE,
  S_DARK_MODE,
  S_LANGUAGE,
  S_ENGLISH,
  S_NEDERLANDS,
  S_POLSKI,
  S_CREDITS,
  S_NARA_BROWSER,
  S_MADE_BY,
  S_POWERED_BY,
  S_LANG_SET_EN,
  S_LANG_SET_NL,
  S_LANG_SET_PL,
  S_LANG_TITLE,
  S_COOKIE_IMPORT_TITLE,
  S_COOKIE_EXPORT_OK,
  S_COOKIE_IMPORT_OK,
  S_COOKIE_NO_FILE,
  S_PW_SAVED,
  S_PW_NO_FORM,
  S_PW_FILL_FORM,
  S_PW_VIEW_TITLE,
  S_PW_NO_PASSWORDS,
  S_PW_CLEAR_OK,
  S_PW_CLEAR_NONE,
  S_PW_AUTOFILL_OK,
  S_PW_AUTOFILL_NONE,
  S_BM_ADDED,
  S_BM_NONE,
  S_BM_TITLE,
  S_DL_COMING,
  S_WV2_NOT_FOUND,
  S_WV2_CANT_CREATE,
  S_CREDITS_TEXT,
  S_CREDITS_TITLE,
  S_TAB_PREFIX,
  S_NIEUWE_TAB,
  S_COOKIE_IMPORT_TEXT,
  S_COOKIE_NONE_TEXT,
  S_SEARCH_PROMPT,
  S_COOKIE_EXPORT_TITLE,
  S_PW_TITLE,
  S_AUTOFILL_TITLE,
  S_PASSWORDS_TITLE,
  S_BOOKMARK_TITLE,
  S_DOWNLOADS_TITLE,
  S_COOKIE_MANAGER_ERROR,
  S_ERROR,
};

struct Translation {
  const wchar_t* s[S_ERROR + 1];
};

static const Translation en = {
  .s = {
    [S_GO] = L"Go",
    [S_SEARCH] = L"\xD83D\xDD0D",
    [S_SETTINGS] = L"\x2699",
    [S_GOOGLE] = L"\xD83D\xDD0D Google",
    [S_PINTEREST] = L"\xD83D\xDCCC Pinterest",
    [S_ROBLOX] = L"\x2B50 Roblox",
    [S_DISCORD] = L"\xD83C\xDFAE Discord",
    [S_SPOTIFY] = L"\xD83C\xDFB5 Spotify",
    [S_DOWNLOADS] = L"\xD83D\xDCE9 Downloads",
    [S_DARK] = L"\xD83C\xDF19 Dark",
    [S_IMPORT] = L"\xD83D\xDCE5 Import",
    [S_EXPORT] = L"\xD83D\xDCE4 Export",
    [S_NEW_TAB] = L"+",
    [S_LIGHT_MODE] = L"Light Mode",
    [S_DARK_MODE] = L"Dark Mode",
    [S_LANGUAGE] = L"Language",
    [S_ENGLISH] = L"English",
    [S_NEDERLANDS] = L"Nederlands",
    [S_POLSKI] = L"Polski",
    [S_CREDITS] = L"Credits",
    [S_NARA_BROWSER] = L"Nara Browser",
    [S_MADE_BY] = L"Made by yutaa",
    [S_POWERED_BY] = L"Powered by WebView2",
    [S_LANG_SET_EN] = L"Language set to English.",
    [S_LANG_SET_NL] = L"Language set to Nederlands.",
    [S_LANG_SET_PL] = L"Język ustawiony na Polski.",
    [S_LANG_TITLE] = L"Language",
    [S_COOKIE_IMPORT_TITLE] = L"Import",
    [S_COOKIE_EXPORT_OK] = L"Cookies exported to cookies.txt",
    [S_COOKIE_IMPORT_OK] = L"cookies imported.",
    [S_COOKIE_NO_FILE] = L"No cookies.txt found.",
    [S_PW_SAVED] = L"Password saved!",
    [S_PW_NO_FORM] = L"No login form found on this page.",
    [S_PW_FILL_FORM] = L"Fill in username and password first.",
    [S_PW_VIEW_TITLE] = L"Saved Passwords",
    [S_PW_NO_PASSWORDS] = L"No saved passwords.",
    [S_PW_CLEAR_OK] = L"All passwords cleared.",
    [S_PW_CLEAR_NONE] = L"No passwords to clear.",
    [S_PW_AUTOFILL_OK] = L"Auto-fill done.",
    [S_PW_AUTOFILL_NONE] = L"No password saved for this site.",
    [S_BM_ADDED] = L"Bookmark added!",
    [S_BM_NONE] = L"No bookmarks.",
    [S_BM_TITLE] = L"Bookmarks",
    [S_DL_COMING] = L"Downloads coming soon!",
    [S_WV2_NOT_FOUND] = L"WebView2 runtime not found.\nInstall from: https://go.microsoft.com/fwlink/p/?LinkId=2124703",
    [S_WV2_CANT_CREATE] = L"Could not create WebView2 controller.",
    [S_CREDITS_TEXT] = L"Nara Browser\n\nMade by yutaa\ngithub.com/kattriley\n\nPowered by WebView2",
    [S_CREDITS_TITLE] = L"Credits",
    [S_TAB_PREFIX] = L"Tab ",
    [S_NIEUWE_TAB] = L"New tab",
    [S_COOKIE_IMPORT_TEXT] = L"cookies imported from: ",
    [S_COOKIE_NONE_TEXT] = L"No cookies found.",
    [S_SEARCH_PROMPT] = L"Search in page:",
    [S_COOKIE_EXPORT_TITLE] = L"Export",
    [S_PW_TITLE] = L"Password",
    [S_AUTOFILL_TITLE] = L"Auto-fill",
    [S_PASSWORDS_TITLE] = L"Passwords",
    [S_BOOKMARK_TITLE] = L"Bookmark",
    [S_DOWNLOADS_TITLE] = L"Downloads",
    [S_COOKIE_MANAGER_ERROR] = L"Cannot open CookieManager.",
    [S_ERROR] = L"Error",
  }
};

static const Translation nl = {
  .s = {
    [S_GO] = L"Go",
    [S_SEARCH] = L"\xD83D\xDD0D",
    [S_SETTINGS] = L"\x2699",
    [S_GOOGLE] = L"\xD83D\xDD0D Google",
    [S_PINTEREST] = L"\xD83D\xDCCC Pinterest",
    [S_ROBLOX] = L"\x2B50 Roblox",
    [S_DISCORD] = L"\xD83C\xDFAE Discord",
    [S_SPOTIFY] = L"\xD83C\xDFB5 Spotify",
    [S_DOWNLOADS] = L"\xD83D\xDCE9 Downloads",
    [S_DARK] = L"\xD83C\xDF19 Donker",
    [S_IMPORT] = L"\xD83D\xDCE5 Importeren",
    [S_EXPORT] = L"\xD83D\xDCE4 Exporteren",
    [S_NEW_TAB] = L"+",
    [S_LIGHT_MODE] = L"Lichte modus",
    [S_DARK_MODE] = L"Donkere modus",
    [S_LANGUAGE] = L"Taal",
    [S_ENGLISH] = L"English",
    [S_NEDERLANDS] = L"Nederlands",
    [S_POLSKI] = L"Polski",
    [S_CREDITS] = L"Credits",
    [S_NARA_BROWSER] = L"Nara Browser",
    [S_MADE_BY] = L"Gemaakt door yutaa",
    [S_POWERED_BY] = L"Mogelijk gemaakt door WebView2",
    [S_LANG_SET_EN] = L"Taal ingesteld op Engels.",
    [S_LANG_SET_NL] = L"Taal ingesteld op Nederlands.",
    [S_LANG_SET_PL] = L"Taal ingesteld op Pools.",
    [S_LANG_TITLE] = L"Taal",
    [S_COOKIE_IMPORT_TITLE] = L"Importeren",
    [S_COOKIE_EXPORT_OK] = L"Cookies geëxporteerd naar cookies.txt",
    [S_COOKIE_IMPORT_OK] = L"cookies geïmporteerd.",
    [S_COOKIE_NO_FILE] = L"Geen cookies.txt gevonden.",
    [S_PW_SAVED] = L"Wachtwoord opgeslagen!",
    [S_PW_NO_FORM] = L"Geen inlogformulier gevonden op deze pagina.",
    [S_PW_FILL_FORM] = L"Vul eerst gebruikersnaam en wachtwoord in.",
    [S_PW_VIEW_TITLE] = L"Opgeslagen Wachtwoorden",
    [S_PW_NO_PASSWORDS] = L"Geen opgeslagen wachtwoorden.",
    [S_PW_CLEAR_OK] = L"Alle wachtwoorden gewist.",
    [S_PW_CLEAR_NONE] = L"Geen wachtwoorden om te wissen.",
    [S_PW_AUTOFILL_OK] = L"Auto-fill uitgevoerd.",
    [S_PW_AUTOFILL_NONE] = L"Geen wachtwoord voor deze site.",
    [S_BM_ADDED] = L"Bookmark toegevoegd!",
    [S_BM_NONE] = L"Geen bookmarks.",
    [S_BM_TITLE] = L"Bookmarks",
    [S_DL_COMING] = L"Downloads komen binnenkort!",
    [S_WV2_NOT_FOUND] = L"WebView2 runtime niet gevonden.\nInstalleer van: https://go.microsoft.com/fwlink/p/?LinkId=2124703",
    [S_WV2_CANT_CREATE] = L"Kon WebView2 controller niet maken.",
    [S_CREDITS_TEXT] = L"Nara Browser\n\nGemaakt door yutaa\ngithub.com/kattriley\n\nMogelijk gemaakt door WebView2",
    [S_CREDITS_TITLE] = L"Credits",
    [S_TAB_PREFIX] = L"Tab ",
    [S_NIEUWE_TAB] = L"Nieuwe tab",
    [S_COOKIE_IMPORT_TEXT] = L"cookies geïmporteerd uit: ",
    [S_COOKIE_NONE_TEXT] = L"Geen cookies gevonden.",
    [S_SEARCH_PROMPT] = L"Zoek op pagina:",
    [S_COOKIE_EXPORT_TITLE] = L"Exporteren",
    [S_PW_TITLE] = L"Wachtwoord",
    [S_AUTOFILL_TITLE] = L"Auto-fill",
    [S_PASSWORDS_TITLE] = L"Wachtwoorden",
    [S_BOOKMARK_TITLE] = L"Bookmark",
    [S_DOWNLOADS_TITLE] = L"Downloads",
    [S_COOKIE_MANAGER_ERROR] = L"Kan CookieManager niet openen.",
    [S_ERROR] = L"Fout",
  }
};

static const Translation pl = {
  .s = {
    [S_GO] = L"Idź",
    [S_SEARCH] = L"\xD83D\xDD0D",
    [S_SETTINGS] = L"\x2699",
    [S_GOOGLE] = L"\xD83D\xDD0D Google",
    [S_PINTEREST] = L"\xD83D\xDCCC Pinterest",
    [S_ROBLOX] = L"\x2B50 Roblox",
    [S_DISCORD] = L"\xD83C\xDFAE Discord",
    [S_SPOTIFY] = L"\xD83C\xDFB5 Spotify",
    [S_DOWNLOADS] = L"\xD83D\xDCE9 Pobieranie",
    [S_DARK] = L"\xD83C\xDF19 Ciemny",
    [S_IMPORT] = L"\xD83D\xDCE5 Importuj",
    [S_EXPORT] = L"\xD83D\xDCE4 Eksportuj",
    [S_NEW_TAB] = L"+",
    [S_LIGHT_MODE] = L"Jasny tryb",
    [S_DARK_MODE] = L"Ciemny tryb",
    [S_LANGUAGE] = L"Język",
    [S_ENGLISH] = L"English",
    [S_NEDERLANDS] = L"Nederlands",
    [S_POLSKI] = L"Polski",
    [S_CREDITS] = L"Twórcy",
    [S_NARA_BROWSER] = L"Nara Browser",
    [S_MADE_BY] = L"Stworzone przez yutaa",
    [S_POWERED_BY] = L"Działa na WebView2",
    [S_LANG_SET_EN] = L"Język zmieniony na angielski.",
    [S_LANG_SET_NL] = L"Język zmieniony na niderlandzki.",
    [S_LANG_SET_PL] = L"Język zmieniony na polski.",
    [S_LANG_TITLE] = L"Język",
    [S_COOKIE_IMPORT_TITLE] = L"Importuj",
    [S_COOKIE_EXPORT_OK] = L"Cookies wyeksportowane do cookies.txt",
    [S_COOKIE_IMPORT_OK] = L"cookies zaimportowane.",
    [S_COOKIE_NO_FILE] = L"Nie znaleziono cookies.txt.",
    [S_PW_SAVED] = L"Hasło zapisane!",
    [S_PW_NO_FORM] = L"Nie znaleziono formularza logowania na tej stronie.",
    [S_PW_FILL_FORM] = L"Wpisz najpierw nazwę użytkownika i hasło.",
    [S_PW_VIEW_TITLE] = L"Zapisane Hasła",
    [S_PW_NO_PASSWORDS] = L"Brak zapisanych haseł.",
    [S_PW_CLEAR_OK] = L"Wszystkie hasła usunięte.",
    [S_PW_CLEAR_NONE] = L"Brak haseł do usunięcia.",
    [S_PW_AUTOFILL_OK] = L"Auto-wypełnienie wykonane.",
    [S_PW_AUTOFILL_NONE] = L"Brak hasła dla tej strony.",
    [S_BM_ADDED] = L"Zakładka dodana!",
    [S_BM_NONE] = L"Brak zakładek.",
    [S_BM_TITLE] = L"Zakładki",
    [S_DL_COMING] = L"Pobieranie wkrótce!",
    [S_WV2_NOT_FOUND] = L"Nie znaleziono WebView2 runtime.\nZainstaluj z: https://go.microsoft.com/fwlink/p/?LinkId=2124703",
    [S_WV2_CANT_CREATE] = L"Nie można utworzyć kontrolera WebView2.",
    [S_CREDITS_TEXT] = L"Nara Browser\n\nStworzone przez yutaa\ngithub.com/kattriley\n\nDziała na WebView2",
    [S_CREDITS_TITLE] = L"Twórcy",
    [S_TAB_PREFIX] = L"Karta ",
    [S_NIEUWE_TAB] = L"Nowa karta",
    [S_COOKIE_IMPORT_TEXT] = L"cookies zaimportowane z: ",
    [S_COOKIE_NONE_TEXT] = L"Nie znaleziono cookies.",
    [S_SEARCH_PROMPT] = L"Szukaj na stronie:",
    [S_COOKIE_EXPORT_TITLE] = L"Eksportuj",
    [S_PW_TITLE] = L"Hasło",
    [S_AUTOFILL_TITLE] = L"Auto-wypełnienie",
    [S_PASSWORDS_TITLE] = L"Hasła",
    [S_BOOKMARK_TITLE] = L"Zakładka",
    [S_DOWNLOADS_TITLE] = L"Pobieranie",
    [S_COOKIE_MANAGER_ERROR] = L"Nie można otworzyć CookieManager.",
    [S_ERROR] = L"Błąd",
  }
};

inline const wchar_t* T(int id) {
  if (id <= 0 || id > S_ERROR) return L"";
  switch (gCurrentLang) {
    case Lang::Nederlands: return nl.s[id];
    case Lang::Polski: return pl.s[id];
    default: return en.s[id];
  }
}
